### ISSUE TITLE
👎 

### ISSUE THREAD

**Issue by unrok** [JackNUMBER/performance-seed-freebox#1]
Bonjour Jack,

L’extension est malheureusement incompatible avec FreeboxOS 4.2 et Chrome 88, malgré la modification du manifest.json vers “*.freeboxos.fr”. Je comprends le manque d’intérêt pour le freenaute lambda… Une mise à jour, même manuelle, est-elle possible ?

Merci à toi.

Johann

**Comment by JackNUMBER** [comment]
Hello @unrok,
Je reprends le développement de l'extension. Avec la version 1.3.0, elle devrait fonctionner avec FreeboxOS 4.5 sur Chrome et elle maintenant disponible sur Firefox 🎉 

Peux-tu me dire si c'est corrigé pour toi ?

**Comment by unrok** [comment]
Hey,

Ça fonctionne en effet.

Merci !

**Comment by JackNUMBER** [comment]
Merci pour la réponse rapide.
Ça n'a pas été mon cas 😂
